[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts",
    "@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable",
    "@foundry-devops/=lib/foundry-devops",
]

# instead of ffi = true, we can use the following settings
fs_permissions = [{ access = "read", path = "./broadcast" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
